Get http://localhost:8080/users

###

Get http://localhost:8080/users/email
Content-Type: application/json

{
    "Email": "johndoe2@gmail.com"
}

###

Get http://localhost:8080/users/password
Content-Type: application/json

{
    "Email": "johndoe2@gmail.com",
    "Password":  "986864656588"
}

###

Get http://localhost:8080/users/logout

###

POST http://localhost:8080/users/adduser
Content-Type: application/json

{
  "Email":  "newguy@gmail.com",
  "Password":  "sf45622355"
}

###

Get http://localhost:8080/gateway

###

Get http://localhost:8080/gateway/getdata

###

POST http://localhost:8080/gateway/adddata
Content-Type: application/json

{
    //copy info from ratingstest2

}

###

PATCH http://localhost:8080/gateway/itemliked
Content-Type: application/json

    [
        {
            "Email": "johndoe2@gmail.com"
        },

        {
            "Company": "Target",
            "Product_id": "160",
            "Store_id": 2845,
            "Availability": "IN_STOCK",
            "Dislikes": "0",
            "Likes": "0",
            "Price": 25.99,
            "Product": "Bobbie Baby Organic Powder Infant Formula - 14oz",
            "Product_family": "Bobbie",
            "Product_img_url": "https://target.scene7.com/is/image/Target/GUEST_a47d490d-8dca-4c78-9993-07a4e630445a",
            "Product_url": "https://www.target.com/p/bobbie-baby-organic-powder-infant-formula-14oz/-/A-85776110",
            "Quantity": -1,
            "Rating": "Unrated"
    
        }
    ]
###

PATCH http://localhost:8080/gateway/itemdisliked
Content-Type: application/json

    [
        {
            "Email": "johndoe2@gmail.com"
        },

        {
            "Company": "Target",
            "Product_id": "160",
            "Store_id": 2845,
            "Availability": "IN_STOCK",
            "Dislikes": "0",
            "Likes": "0",
            "Price": 25.99,
            "Product": "Bobbie Baby Organic Powder Infant Formula - 14oz",
            "Product_family": "Bobbie",
            "Product_img_url": "https://target.scene7.com/is/image/Target/GUEST_a47d490d-8dca-4c78-9993-07a4e630445a",
            "Product_url": "https://www.target.com/p/bobbie-baby-organic-powder-infant-formula-14oz/-/A-85776110",
            "Quantity": -1,
            "Rating": "Unrated"
    
        }
    ]


